# NumPy科学计算

NumPy是Python科学计算的基础库，提供了高性能的多维数组对象以及用于处理这些数组的各种工具。

## 学习目标
- 理解NumPy的核心概念和ndarray对象
- 掌握数组的创建、索引和切片方法
- 理解NumPy的数据类型系统和广播机制
- 熟练使用NumPy的常用数学和统计函数

## 1. ndarray对象简介

ndarray（N-dimensional Array）是NumPy的核心数据结构，代表N维数组。

### 1.1 多维性

ndarray支持从0维（标量）到任意高维数组。

In [72]:
import numpy as np

# 0维数组（标量）
arr = np.array(5)
print('0维数组:', arr)
print('维度:', arr.ndim)

0维数组: 5
维度: 0


In [73]:
# 1维数组（向量）
arr = np.array([1, 2, 3, 4, 5])
print('1维数组:', arr)
print('维度:', arr.ndim)
print('形状:', arr.shape)

1维数组: [1 2 3 4 5]
维度: 1
形状: (5,)


In [74]:
# 2维数组（矩阵）
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('2维数组:')
print(arr)
print('维度:', arr.ndim)
print('形状:', arr.shape)

2维数组:
[[1 2 3]
 [4 5 6]]
维度: 2
形状: (2, 3)


In [75]:
# 3维数组
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('3维数组形状:', arr.shape)
print('维度:', arr.ndim)

3维数组形状: (2, 2, 2)
维度: 3


### 1.2 同质性

数组中的所有元素必须是相同类型，混合类型会自动转换。

In [76]:
# 整数和浮点数混合 - 整数会被提升为浮点数
arr = np.array([1, 2.5, 3])
print('类型:', arr.dtype)
print('值:', arr)

类型: float64
值: [1.  2.5 3. ]


In [77]:
# 不同类型字符串
arr = np.array(['hello', 'world'])
print('类型:', arr.dtype)

类型: <U5


## 2. ndarray的属性

ndarray对象有多个重要属性用于描述其结构特征。

In [78]:
# 创建示例数组
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print('数组:')
print(arr)
print()
print('shape (形状):', arr.shape, '- 行数和列数')
print('ndim (维度):', arr.ndim, '- 维度数量')
print('size (元素数):', arr.size, '- 总元素个数')
print('dtype (类型):', arr.dtype, '- 元素数据类型')
print('itemsize (元素字节):', arr.itemsize, '- 单个元素占用的字节')
print('nbytes (总字节):', arr.nbytes, '- 整个数组占用的字节')

数组:
[[1. 2. 3.]
 [4. 5. 6.]]

shape (形状): (2, 3) - 行数和列数
ndim (维度): 2 - 维度数量
size (元素数): 6 - 总元素个数
dtype (类型): float64 - 元素数据类型
itemsize (元素字节): 8 - 单个元素占用的字节
nbytes (总字节): 48 - 整个数组占用的字节


In [79]:
# 转置
print('转置:')
print(arr.T)
print('转置形状:', arr.T.shape)

转置:
[[1. 4.]
 [2. 5.]
 [3. 6.]]
转置形状: (3, 2)


## 3. 创建ndarray数组

NumPy提供了多种创建数组的方法。

In [80]:
# 从列表创建
arr = np.array([1, 2, 3, 4, 5])
print('从列表创建:', arr)

# 指定数据类型
arr = np.array([1, 2, 3], dtype=np.float32)
print('指定float32类型:', arr, '- dtype:', arr.dtype)

从列表创建: [1 2 3 4 5]
指定float32类型: [1. 2. 3.] - dtype: float32


In [81]:
# 预定义形状的数组
print('全0数组 (2x3):')
print(np.zeros((2, 3)))

print('全1数组 (3x2, int类型):')
print(np.ones((3, 2), dtype=int))

print('自定义值数组 (2x3, 全部为5):')
print(np.full((2, 3), 5))

全0数组 (2x3):
[[0. 0. 0.]
 [0. 0. 0.]]
全1数组 (3x2, int类型):
[[1 1]
 [1 1]
 [1 1]]
自定义值数组 (2x3, 全部为5):
[[5 5 5]
 [5 5 5]]


In [82]:
# 未初始化数组（值随机）
print('未初始化数组:')
print(np.empty((2, 2)))

未初始化数组:
[[     nan 0.0e+000]
 [9.9e-324 1.5e-323]]


In [83]:
# 等差数列
arr = np.arange(1, 11, 2)  # start, stop, step
print('arange (1到10, 步长2):', arr)

# 等间隔数组
arr = np.linspace(0, 1, 5)  # start, stop, num
print('linspace (0到1, 5个点):', arr)

# 对数间隔
arr = np.logspace(0, 2, 3, base=2)  # 2^0, 2^1, 2^2
print('logspace (2^0到2^2, 3个点):', arr)

arange (1到10, 步长2): [1 3 5 7 9]
linspace (0到1, 5个点): [0.   0.25 0.5  0.75 1.  ]
logspace (2^0到2^2, 3个点): [1. 2. 4.]


In [84]:
# 特殊矩阵
print('单位矩阵 (3x3):')
print(np.eye(3))

print('对角矩阵:')
print(np.diag([5, 1, 2, 3]))

单位矩阵 (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
对角矩阵:
[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


## 4. 随机数组生成

随机数组在模拟、初始化、抽样等场景中非常有用。

In [85]:
# 均匀分布随机数 [0, 1)
print('uniform分布 [0,1):')
print(np.random.rand(2, 3))

# 指定范围均匀分布
print('uniform分布 [3, 6):')
print(np.random.uniform(3, 6, (2, 3)))

uniform分布 [0,1):
[[0.14814086 0.98182939 0.47837031]
 [0.49739137 0.63947252 0.36858461]]
uniform分布 [3, 6):
[[3.41070082 5.4663532  3.56954374]
 [4.53395695 3.67295109 3.29353345]]


In [86]:
# 正态分布随机数（均值0, 标准差1）
print('正态分布 (均值0, 标准差1):')
print(np.random.randn(2, 3))

# 随机整数
print('随机整数 [1, 10):')
print(np.random.randint(1, 10, (2, 3)))

正态分布 (均值0, 标准差1):
[[-0.69277058  1.13782687 -0.16915725]
 [-0.76391367 -0.4980731  -0.36289111]]
随机整数 [1, 10):
[[3 2 3]
 [2 4 5]]


In [87]:
# 设置随机种子（保证结果可复现）
np.random.seed(42)
print('设置种子42后的随机数组:')
print(np.random.rand(5))

# 再次设置相同种子
np.random.seed(42)
print('再次设置种子42:')
print(np.random.rand(5))

设置种子42后的随机数组:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
再次设置种子42:
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


## 5. 数据类型

NumPy支持丰富的数据类型。

In [88]:
# 布尔类型
arr = np.array([True, False, True])
print('bool数组:', arr, '- dtype:', arr.dtype)

# 整数类型
arr = np.array([1, 2, 127], dtype=np.int8)  # int8: -128到127
print('int8数组:', arr)

# 无符号整数
arr = np.array([255, 128], dtype=np.uint8)  # uint8: 0到255
print('uint8数组:', arr)

bool数组: [ True False  True] - dtype: bool
int8数组: [  1   2 127]
uint8数组: [255 128]


In [89]:
# 类型转换
arr = np.array([1.5, 2.7, 3.9])
print('float64:', arr, arr.dtype)

int_arr = arr.astype(np.int32)
print('转换为int32:', int_arr, int_arr.dtype)

float64: [1.5 2.7 3.9] float64
转换为int32: [1 2 3] int32


## 6. 索引与切片

NumPy数组支持丰富多样的索引方式。

In [90]:
# 一维数组索引
arr = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
print('原数组:', arr)
print('arr[2]:', arr[2])
print('arr[2:5]:', arr[2:5])  # 左闭右开
print('arr[::2]:', arr[::2])  # 步长2
print('arr[::-1]:', arr[::-1])  # 反转

原数组: [0 1 2 3 4 5 6 7 8 9]
arr[2]: 2
arr[2:5]: [2 3 4]
arr[::2]: [0 2 4 6 8]
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]


In [91]:
# 二维数组索引
arr = np.arange(12).reshape(3, 4)
print('2D数组:')
print(arr)
print()
print('arr[1, 2]:', arr[1, 2], '- 第2行第3列')
print('arr[0, :]:', arr[0, :], '- 第1行')
print('arr[:, 1]:', arr[:, 1], '- 第2列')
print('arr[0:2, 1:3]:')  # 前2行，2-3列
print(arr[0:2, 1:3])

2D数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

arr[1, 2]: 6 - 第2行第3列
arr[0, :]: [0 1 2 3] - 第1行
arr[:, 1]: [1 5 9] - 第2列
arr[0:2, 1:3]:
[[1 2]
 [5 6]]


In [92]:
# 布尔索引
arr = np.arange(1, 10)
print('原数组:', arr)

# 筛选大于5的元素
print('arr > 5:', arr > 5)
print('arr[arr > 5]:', arr[arr > 5])

# 组合条件
print('(arr > 3) & (arr < 8):', arr[(arr > 3) & (arr < 8)])

原数组: [1 2 3 4 5 6 7 8 9]
arr > 5: [False False False False False  True  True  True  True]
arr[arr > 5]: [6 7 8 9]
(arr > 3) & (arr < 8): [4 5 6 7]


In [93]:
# 花式索引
arr = np.arange(10, 20)
print('原数组:', arr)
print('arr[[2, 5, 8]]:', arr[[2, 5, 8]])  # 按指定索引选取
print('arr[[-1, -2]]:', arr[[-1, -2]])  # 负索引

原数组: [10 11 12 13 14 15 16 17 18 19]
arr[[2, 5, 8]]: [12 15 18]
arr[[-1, -2]]: [19 18]


## 7. 基本运算与广播机制

NumPy支持向量化运算，无需循环即可对整个数组进行计算。

In [94]:
# 数组与数组运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)
print('a / b:', a / b)
print('a ** 2:', a ** 2)

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a ** 2: [1 4 9]


In [95]:
# 数组与标量运算
a = np.array([1, 2, 3])
print('a + 10:', a + 10)
print('a * 2:', a * 2)
print('a ** 2:', a ** 2)

a + 10: [11 12 13]
a * 2: [2 4 6]
a ** 2: [1 4 9]


In [96]:
# 广播机制
# 当两个数组形状不同时，NumPy会自动进行广播

# 示例1：1维 + 2维
a = np.array([[1], [2], [3]])  # shape (3, 1)
b = np.array([10, 20, 30])       # shape (3,)
print('a (3x1):')
print(a)
print('b (3,):')
print(b)
print('a + b (广播):')
print(a + b)

a (3x1):
[[1]
 [2]
 [3]]
b (3,):
[10 20 30]
a + b (广播):
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [97]:
# 示例2：标量与数组
a = np.array([1, 2, 3])
print('标量5广播到数组:', a + 5)

# 注意：形状不兼容时会报错
try:
    a = np.array([1, 2, 3])
    b = np.array([4, 5])
    print(a + b)
except ValueError as e:
    print('错误:', e)

标量5广播到数组: [6 7 8]
错误: operands could not be broadcast together with shapes (3,) (2,) 


In [98]:
# 矩阵乘法 @ 运算符
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('矩阵乘法 a @ b:')
print(a @ b)

# 或者使用 np.dot
print('np.dot(a, b):')
print(np.dot(a, b))

矩阵乘法 a @ b:
[[19 22]
 [43 50]]
np.dot(a, b):
[[19 22]
 [43 50]]


## 8. 常用数学函数

NumPy提供了丰富的数学函数。

In [99]:
# 基本数学函数
arr = np.array([1, 4, 9, 16])
print('sqrt:', np.sqrt(arr))  # 平方根
print('exp:', np.exp(np.array([0, 1, 2])))  # e^x
print('log:', np.log(np.array([1, np.e, np.e**2])))  # 自然对数
print('abs:', np.abs(np.array([-1, -2.5, 3])))  # 绝对值
print('power:', np.power(2, np.array([3, 4, 5])))  # 2^x

sqrt: [1. 2. 3. 4.]
exp: [1.         2.71828183 7.3890561 ]
log: [0. 1. 2.]
abs: [1.  2.5 3. ]
power: [ 8 16 32]


In [100]:
# 三角函数
arr = np.array([0, np.pi/6, np.pi/2, np.pi])
print('sin:', np.sin(arr))
print('cos:', np.cos(arr))

sin: [0.0000000e+00 5.0000000e-01 1.0000000e+00 1.2246468e-16]
cos: [ 1.00000000e+00  8.66025404e-01  6.12323400e-17 -1.00000000e+00]


In [101]:
# 取整函数
arr = np.array([1.2, 2.5, 3.7, -1.3])
print('ceil (向上取整):', np.ceil(arr))
print('floor (向下取整):', np.floor(arr))
print('round (四舍五入):', np.round(arr))
print('rint (四舍五入到偶数):', np.rint(np.array([1.5, 2.5, 3.5])))

ceil (向上取整): [ 2.  3.  4. -1.]
floor (向下取整): [ 1.  2.  3. -2.]
round (四舍五入): [ 1.  2.  4. -1.]
rint (四舍五入到偶数): [2. 2. 4.]


## 9. 统计函数

NumPy提供了全面的统计计算功能。

In [102]:
arr = np.array([1, 5, 3, 2, 4, 8, 6, 7])
print('数组:', arr)
print('sum:', np.sum(arr))
print('mean:', np.mean(arr))
print('median:', np.median(arr))
print('std:', np.std(arr))  # 标准差
print('var:', np.var(arr))  # 方差
print('min:', np.min(arr))
print('max:', np.max(arr))
print('argmin:', np.argmin(arr), '- 最小值索引')
print('argmax:', np.argmax(arr), '- 最大值索引')

数组: [1 5 3 2 4 8 6 7]
sum: 36
mean: 4.5
median: 4.5
std: 2.29128784747792
var: 5.25
min: 1
max: 8
argmin: 0 - 最小值索引
argmax: 5 - 最大值索引


In [103]:
# 分位数
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print('数组:', arr)
print('25%分位数:', np.percentile(arr, 25))
print('50%分位数:', np.percentile(arr, 50))
print('75%分位数:', np.percentile(arr, 75))

数组: [ 1  2  3  4  5  6  7  8  9 10]
25%分位数: 3.25
50%分位数: 5.5
75%分位数: 7.75


In [104]:
# 累积函数
arr = np.array([1, 2, 3, 4, 5])
print('数组:', arr)
print('cumsum (累积和):', np.cumsum(arr))  # [1, 1+2, 1+2+3, ...]
print('cumprod (累积积):', np.cumprod(arr))  # [1, 1*2, 1*2*3, ...]

数组: [1 2 3 4 5]
cumsum (累积和): [ 1  3  6 10 15]
cumprod (累积积): [  1   2   6  24 120]


In [105]:
# 多维数组按轴计算
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('数组:')
print(arr)
print()
print('按列求和 (axis=0):', np.sum(arr, axis=0))
print('按行求和 (axis=1):', np.sum(arr, axis=1))
print('按列均值:', np.mean(arr, axis=0))

数组:
[[1 2 3]
 [4 5 6]]

按列求和 (axis=0): [5 7 9]
按行求和 (axis=1): [ 6 15]
按列均值: [2.5 3.5 4.5]


## 10. 比较函数

NumPy提供了元素级的比较操作。

In [106]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
print('a:', a)
print('b:', b)
print('a > b:', np.greater(a, b))
print('a < b:', np.less(a, b))
print('a == b:', np.equal(a, b))

a: [1 2 3]
b: [3 2 1]
a > b: [False False  True]
a < b: [ True False False]
a == b: [False  True False]


In [107]:
# 逻辑函数
a = np.array([True, False, True])
b = np.array([True, True, False])
print('logical_and:', np.logical_and(a, b))
print('logical_or:', np.logical_or(a, b))
print('logical_not a:', np.logical_not(a))

# any 和 all
print('any([True, False]):', np.any([True, False]))
print('all([True, False]):', np.all([True, False]))

logical_and: [ True False False]
logical_or: [ True  True  True]
logical_not a: [False  True False]
any([True, False]): True
all([True, False]): False


In [108]:
# np.where 条件选择
a = np.array([1, 2, 3, 4, 5])
print('where条件选择:')
print(np.where(a > 3, '大', '小'))

# 也可以用于替换
print(np.where(a > 3, a * 2, a))

where条件选择:
['小' '小' '小' '大' '大']
[ 1  2  3  8 10]


## 11. 排序与去重

NumPy提供了排序和去重功能。

In [109]:
arr = np.array([3, 1, 2, 5, 4])
print('原数组:', arr)
print('排序副本:', np.sort(arr))
print('原数组不变:', arr)

# 原地排序
arr.sort()
print('原地排序后:', arr)

原数组: [3 1 2 5 4]
排序副本: [1 2 3 4 5]
原数组不变: [3 1 2 5 4]
原地排序后: [1 2 3 4 5]


In [110]:
# 返回排序后的索引
arr = np.array([3, 1, 2, 5, 4])
print('argsort:', np.argsort(arr))  # 排序后应该在的位置

argsort: [1 2 0 4 3]


In [111]:
# 去重
arr = np.array([1, 2, 2, 3, 3, 3, 4])
print('unique:', np.unique(arr))

# 返回出现次数
unique, counts = np.unique(arr, return_counts=True)
print('唯一值:', unique)
print('出现次数:', counts)

unique: [1 2 3 4]
唯一值: [1 2 3 4]
出现次数: [1 2 3 1]


## 12. 数组操作

NumPy提供了多种数组拼接、分割、变形操作。

In [112]:
# 拼接
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('水平拼接:', np.concatenate((a, b)))

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print('垂直拼接:')
print(np.vstack((a, b)))

水平拼接: [1 2 3 4 5 6]
垂直拼接:
[[1 2]
 [3 4]
 [5 6]]


In [113]:
# 分割
arr = np.array([1, 2, 3, 4, 5, 6])
print('分割为3部分:', np.split(arr, 3))
print('按索引分割:', np.split(arr, [2, 4]))  # [0:2], [2:4], [4:]

分割为3部分: [array([1, 2]), array([3, 4]), array([5, 6])]
按索引分割: [array([1, 2]), array([3, 4]), array([5, 6])]


In [114]:
# reshape 变形
arr = np.arange(12)
print('变形为3x4:')
print(arr.reshape(3, 4))

print('变形为4x3:')
print(arr.reshape(4, 3))

# -1自动计算
print('自动计算列数:')
print(arr.reshape(3, -1))

变形为3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
变形为4x3:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
自动计算列数:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [115]:
# 复制
arr = np.array([1, 2, 3])
arr_copy = arr.copy()  # 深拷贝
arr_copy[0] = 100
print('原数组:', arr)
print('拷贝修改后:', arr_copy)

原数组: [1 2 3]
拷贝修改后: [100   2   3]


## 13. 缺失值处理

NumPy使用np.nan表示缺失值。

In [116]:
arr = np.array([1, np.nan, 3, np.nan, 5])
print('数组:', arr)
print('isnan:', np.isnan(arr))
print('非缺失值数量:', np.sum(~np.isnan(arr)))

# 替换缺失值
arr[np.isnan(arr)] = 0
print('替换后:', arr)

数组: [ 1. nan  3. nan  5.]
isnan: [False  True False  True False]
非缺失值数量: 3
替换后: [1. 0. 3. 0. 5.]


## 14. 综合练习

### 练习1：温度分析

某城市一周的最高气温（℃）：[28, 30, 29, 31, 32, 30, 29]

In [117]:
import numpy as np

temps = np.array([28, 30, 29, 31, 32, 30, 29])

print('平均气温:', np.mean(temps).round(2), '℃')
print('最高气温:', np.max(temps), '℃')
print('最低气温:', np.min(temps), '℃')
print('气温超过30℃的天数:', np.sum(temps > 30))
print('超过30℃的日期:', np.where(temps > 30)[0] + 1, '日')

平均气温: 29.86 ℃
最高气温: 32 ℃
最低气温: 28 ℃
气温超过30℃的天数: 2
超过30℃的日期: [4 5] 日


### 练习2：学生成绩统计

某班级5名学生的成绩：[85, 90, 78, 92, 88]

In [118]:
scores = np.array([85, 90, 78, 92, 88])

print('平均分:', np.mean(scores).round(2))
print('中位数:', np.median(scores))
print('标准差:', np.std(scores).round(2))
print('最高分:', np.max(scores))
print('最低分:', np.min(scores))

平均分: 86.6
中位数: 88.0
标准差: 4.88
最高分: 92
最低分: 78


### 练习3：矩阵运算

In [119]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('A + B (对应元素相加):')
print(A + B)

print('A * B (对应元素相乘):')
print(A * B)

print('A @ B (矩阵乘法):')
print(A @ B)

A + B (对应元素相加):
[[ 6  8]
 [10 12]]
A * B (对应元素相乘):
[[ 5 12]
 [21 32]]
A @ B (矩阵乘法):
[[19 22]
 [43 50]]


### 练习4：布尔索引应用

生成随机数组，筛选满足条件的元素。

In [120]:
np.random.seed(42)
arr = np.random.randint(0, 50, 20)
print('随机数组:', arr)

print('大于30的元素:', arr[arr > 30])
print('在10到25之间的元素:', arr[(arr >= 10) & (arr <= 25)])

# 替换满足条件的元素
arr[(arr > 40)] = 0
print('将大于40的替换为0:', arr)

随机数组: [38 28 14 42  7 20 38 18 22 10 10 23 35 39 23  2 21  1 23 43]
大于30的元素: [38 42 38 35 39 43]
在10到25之间的元素: [14 20 18 22 10 10 23 23 21 23]
将大于40的替换为0: [38 28 14  0  7 20 38 18 22 10 10 23 35 39 23  2 21  1 23  0]
